<?php

$labels = array();
$labels['pass_is'] = 'Your Password is';
$labels['captcha_wrong'] = 'The captcha is wrong';
$labels['answer_wrong'] = 'The answer is wrong';
$labels['captcha_answer_wrong'] = 'The captcha and the aswer are wrong';
$labels['no_username'] = 'You have not set an username in the previous form';
$labels['back'] = 'Back';
$labels['question'] = 'Question:';
$labels['answer'] = 'Answer:';
$labels['submit'] = 'Submit';
$labels['no_secret'] = 'You have not set a secret question';
$labels['recover_pass'] = 'Recover Password';
$labels['match'] = 'Make the math';
$labels['letters'] = 'Write the characters, not the numbers';
$labels['numbers'] = 'Write the numbers, not the characters';
?>

