<?php

$labels = array();
$labels['recover_pass'] = 'Secret Question';
$labels['no_recover_pass_set'] = 'No Secret Question Set';
$labels['recover_pass_question'] = 'Password Recovery Question:';
$labels['recover_pass_answer_1'] = 'Password Recovery Answer:';
$labels['recover_pass_answer_2'] = 'Confirm Password Recovery Answer:';
$labels['recover_pass_set'] = 'Secret question Set';
$labels['recover_pass_current_pass_1'] = 'Current Password';
$labels['recover_pass_current_pass_2'] = 'Confirm Current Password';
$labels['error'] = 'Error';
$labels['of'] = 'of';
$labels['has'] = 'has';
$labels['save'] = 'Your Secret Question has been saved successfully';
$labels['save_fail'] = 'Your Secret Question has not been saved';
$labels['no_msg'] = 'No vacation message set';
$labels['delete'] = 'Your vacation recipe has beed deleted successfully';
$labels['days'] = 'days';
$labels['save_button'] = 'save';
$labels['delete_button'] = 'delete';
$labels['no_secret_question'] = 'You have not inserted a Question';
$labels['no_secret_answer'] = 'You have not set a secret question Answer';
$labels['no_secret_answer_confirm'] = 'You have not confirmed the secret question Answer';
$labels['no_current_pass'] = 'You have not set your current Password';
$labels['no_current_pass_confirm'] = 'You have not confirmed the current Password';
$labels['no_match_question'] = 'No match in the secret question answers';
$labels['no_match_pass'] = 'No match in the current password answers';
$labels['recover_email'] = 'E-mail recovery address:';
?>
